// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: chat-service-pb/chat.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsGroup        bool                   `protobuf:"varint,3,opt,name=is_group,json=isGroup,proto3" json:"is_group,omitempty"`
	ParticipantIds []string               `protobuf:"bytes,4,rep,name=participant_ids,json=participantIds,proto3" json:"participant_ids,omitempty"`
	CreatorId      string                 `protobuf:"bytes,5,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastMessage    *ChatMessage           `protobuf:"bytes,7,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Chat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chat) GetIsGroup() bool {
	if x != nil {
		return x.IsGroup
	}
	return false
}

func (x *Chat) GetParticipantIds() []string {
	if x != nil {
		return x.ParticipantIds
	}
	return nil
}

func (x *Chat) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Chat) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Chat) GetLastMessage() *ChatMessage {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	IsEdited      bool                   `protobuf:"varint,5,opt,name=is_edited,json=isEdited,proto3" json:"is_edited,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetIsEdited() bool {
	if x != nil {
		return x.IsEdited
	}
	return false
}

func (x *ChatMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChatMessage) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatsRequest) Reset() {
	*x = GetChatsRequest{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatsRequest) ProtoMessage() {}

func (x *GetChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatsRequest.ProtoReflect.Descriptor instead.
func (*GetChatsRequest) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{2}
}

type GetChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatsResponse) Reset() {
	*x = GetChatsResponse{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatsResponse) ProtoMessage() {}

func (x *GetChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatsResponse.ProtoReflect.Descriptor instead.
func (*GetChatsResponse) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{3}
}

func (x *GetChatsResponse) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

type CreateDirectChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId  string                 `protobuf:"bytes,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectChatRequest) Reset() {
	*x = CreateDirectChatRequest{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectChatRequest) ProtoMessage() {}

func (x *CreateDirectChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectChatRequest.ProtoReflect.Descriptor instead.
func (*CreateDirectChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDirectChatRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type CreateDirectChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectChatResponse) Reset() {
	*x = CreateDirectChatResponse{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectChatResponse) ProtoMessage() {}

func (x *CreateDirectChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectChatResponse.ProtoReflect.Descriptor instead.
func (*CreateDirectChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDirectChatResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type CreateGroupChatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParticipantIds []string               `protobuf:"bytes,2,rep,name=participant_ids,json=participantIds,proto3" json:"participant_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateGroupChatRequest) Reset() {
	*x = CreateGroupChatRequest{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupChatRequest) ProtoMessage() {}

func (x *CreateGroupChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupChatRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{6}
}

func (x *CreateGroupChatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupChatRequest) GetParticipantIds() []string {
	if x != nil {
		return x.ParticipantIds
	}
	return nil
}

type CreateGroupChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupChatResponse) Reset() {
	*x = CreateGroupChatResponse{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupChatResponse) ProtoMessage() {}

func (x *CreateGroupChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupChatResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{7}
}

func (x *CreateGroupChatResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ChatMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{9}
}

func (x *SendMessageResponse) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{10}
}

func (x *GetMessagesRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetMessagesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMessagesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{11}
}

func (x *GetMessagesResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetMessagesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type EditMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	NewContent    string                 `protobuf:"bytes,3,opt,name=new_content,json=newContent,proto3" json:"new_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMessageRequest) Reset() {
	*x = EditMessageRequest{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMessageRequest) ProtoMessage() {}

func (x *EditMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMessageRequest.ProtoReflect.Descriptor instead.
func (*EditMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{12}
}

func (x *EditMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EditMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *EditMessageRequest) GetNewContent() string {
	if x != nil {
		return x.NewContent
	}
	return ""
}

type EditMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ChatMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMessageResponse) Reset() {
	*x = EditMessageResponse{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMessageResponse) ProtoMessage() {}

func (x *EditMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMessageResponse.ProtoReflect.Descriptor instead.
func (*EditMessageResponse) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{13}
}

func (x *EditMessageResponse) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DeleteMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type DeleteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageResponse) Reset() {
	*x = DeleteMessageResponse{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageResponse) ProtoMessage() {}

func (x *DeleteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SendReadReceiptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendReadReceiptRequest) Reset() {
	*x = SendReadReceiptRequest{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendReadReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReadReceiptRequest) ProtoMessage() {}

func (x *SendReadReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReadReceiptRequest.ProtoReflect.Descriptor instead.
func (*SendReadReceiptRequest) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{16}
}

func (x *SendReadReceiptRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendReadReceiptRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type SendReadReceiptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendReadReceiptResponse) Reset() {
	*x = SendReadReceiptResponse{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendReadReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReadReceiptResponse) ProtoMessage() {}

func (x *SendReadReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReadReceiptResponse.ProtoReflect.Descriptor instead.
func (*SendReadReceiptResponse) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{17}
}

func (x *SendReadReceiptResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SendTypingStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	IsTyping      bool                   `protobuf:"varint,2,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTypingStatusRequest) Reset() {
	*x = SendTypingStatusRequest{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTypingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTypingStatusRequest) ProtoMessage() {}

func (x *SendTypingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTypingStatusRequest.ProtoReflect.Descriptor instead.
func (*SendTypingStatusRequest) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{18}
}

func (x *SendTypingStatusRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendTypingStatusRequest) GetIsTyping() bool {
	if x != nil {
		return x.IsTyping
	}
	return false
}

type SendTypingStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTypingStatusResponse) Reset() {
	*x = SendTypingStatusResponse{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTypingStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTypingStatusResponse) ProtoMessage() {}

func (x *SendTypingStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTypingStatusResponse.ProtoReflect.Descriptor instead.
func (*SendTypingStatusResponse) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{19}
}

func (x *SendTypingStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AddParticipantToGroupChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddParticipantToGroupChatRequest) Reset() {
	*x = AddParticipantToGroupChatRequest{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddParticipantToGroupChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddParticipantToGroupChatRequest) ProtoMessage() {}

func (x *AddParticipantToGroupChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddParticipantToGroupChatRequest.ProtoReflect.Descriptor instead.
func (*AddParticipantToGroupChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{20}
}

func (x *AddParticipantToGroupChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *AddParticipantToGroupChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AddParticipantToGroupChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddParticipantToGroupChatResponse) Reset() {
	*x = AddParticipantToGroupChatResponse{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddParticipantToGroupChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddParticipantToGroupChatResponse) ProtoMessage() {}

func (x *AddParticipantToGroupChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddParticipantToGroupChatResponse.ProtoReflect.Descriptor instead.
func (*AddParticipantToGroupChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{21}
}

func (x *AddParticipantToGroupChatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RemoveParticipantFromGroupChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveParticipantFromGroupChatRequest) Reset() {
	*x = RemoveParticipantFromGroupChatRequest{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveParticipantFromGroupChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveParticipantFromGroupChatRequest) ProtoMessage() {}

func (x *RemoveParticipantFromGroupChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveParticipantFromGroupChatRequest.ProtoReflect.Descriptor instead.
func (*RemoveParticipantFromGroupChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{22}
}

func (x *RemoveParticipantFromGroupChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *RemoveParticipantFromGroupChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveParticipantFromGroupChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveParticipantFromGroupChatResponse) Reset() {
	*x = RemoveParticipantFromGroupChatResponse{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveParticipantFromGroupChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveParticipantFromGroupChatResponse) ProtoMessage() {}

func (x *RemoveParticipantFromGroupChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveParticipantFromGroupChatResponse.ProtoReflect.Descriptor instead.
func (*RemoveParticipantFromGroupChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveParticipantFromGroupChatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type EditGroupChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditGroupChatRequest) Reset() {
	*x = EditGroupChatRequest{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditGroupChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditGroupChatRequest) ProtoMessage() {}

func (x *EditGroupChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditGroupChatRequest.ProtoReflect.Descriptor instead.
func (*EditGroupChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{24}
}

func (x *EditGroupChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *EditGroupChatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EditGroupChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditGroupChatResponse) Reset() {
	*x = EditGroupChatResponse{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditGroupChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditGroupChatResponse) ProtoMessage() {}

func (x *EditGroupChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditGroupChatResponse.ProtoReflect.Descriptor instead.
func (*EditGroupChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{25}
}

func (x *EditGroupChatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteGroupChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupChatRequest) Reset() {
	*x = DeleteGroupChatRequest{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupChatRequest) ProtoMessage() {}

func (x *DeleteGroupChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupChatRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteGroupChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type DeleteGroupChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupChatResponse) Reset() {
	*x = DeleteGroupChatResponse{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupChatResponse) ProtoMessage() {}

func (x *DeleteGroupChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupChatResponse.ProtoReflect.Descriptor instead.
func (*DeleteGroupChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteGroupChatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LeaveGroupChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupChatRequest) Reset() {
	*x = LeaveGroupChatRequest{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupChatRequest) ProtoMessage() {}

func (x *LeaveGroupChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupChatRequest.ProtoReflect.Descriptor instead.
func (*LeaveGroupChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{28}
}

func (x *LeaveGroupChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type LeaveGroupChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupChatResponse) Reset() {
	*x = LeaveGroupChatResponse{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupChatResponse) ProtoMessage() {}

func (x *LeaveGroupChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupChatResponse.ProtoReflect.Descriptor instead.
func (*LeaveGroupChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{29}
}

func (x *LeaveGroupChatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StreamMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessagesRequest) Reset() {
	*x = StreamMessagesRequest{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesRequest) ProtoMessage() {}

func (x *StreamMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesRequest.ProtoReflect.Descriptor instead.
func (*StreamMessagesRequest) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{30}
}

func (x *StreamMessagesRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *StreamMessagesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type StreamMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ChatMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessagesResponse) Reset() {
	*x = StreamMessagesResponse{}
	mi := &file_chat_service_pb_chat_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesResponse) ProtoMessage() {}

func (x *StreamMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_service_pb_chat_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesResponse.ProtoReflect.Descriptor instead.
func (*StreamMessagesResponse) Descriptor() ([]byte, []int) {
	return file_chat_service_pb_chat_proto_rawDescGZIP(), []int{31}
}

func (x *StreamMessagesResponse) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_chat_service_pb_chat_proto protoreflect.FileDescriptor

const file_chat_service_pb_chat_proto_rawDesc = "" +
	"\n" +
	"\x1achat-service-pb/chat.proto\x12\x06chatpb\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x02\n" +
	"\x04Chat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bis_group\x18\x03 \x01(\bR\aisGroup\x12'\n" +
	"\x0fparticipant_ids\x18\x04 \x03(\tR\x0eparticipantIds\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x05 \x01(\tR\tcreatorId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x126\n" +
	"\flast_message\x18\a \x01(\v2\x13.chatpb.ChatMessageR\vlastMessage\"\x80\x02\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1b\n" +
	"\tis_edited\x18\x05 \x01(\bR\bisEdited\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x11\n" +
	"\x0fGetChatsRequest\"6\n" +
	"\x10GetChatsResponse\x12\"\n" +
	"\x05chats\x18\x01 \x03(\v2\f.chatpb.ChatR\x05chats\"?\n" +
	"\x17CreateDirectChatRequest\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\tR\ftargetUserId\"<\n" +
	"\x18CreateDirectChatResponse\x12 \n" +
	"\x04chat\x18\x01 \x01(\v2\f.chatpb.ChatR\x04chat\"U\n" +
	"\x16CreateGroupChatRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fparticipant_ids\x18\x02 \x03(\tR\x0eparticipantIds\";\n" +
	"\x17CreateGroupChatResponse\x12 \n" +
	"\x04chat\x18\x01 \x01(\v2\f.chatpb.ChatR\x04chat\"G\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"D\n" +
	"\x13SendMessageResponse\x12-\n" +
	"\amessage\x18\x01 \x01(\v2\x13.chatpb.ChatMessageR\amessage\"^\n" +
	"\x12GetMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"g\n" +
	"\x13GetMessagesResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.chatpb.ChatMessageR\bmessages\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"m\n" +
	"\x12EditMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x1f\n" +
	"\vnew_content\x18\x03 \x01(\tR\n" +
	"newContent\"D\n" +
	"\x13EditMessageResponse\x12-\n" +
	"\amessage\x18\x01 \x01(\v2\x13.chatpb.ChatMessageR\amessage\"N\n" +
	"\x14DeleteMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\"/\n" +
	"\x15DeleteMessageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"P\n" +
	"\x16SendReadReceiptRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"1\n" +
	"\x17SendReadReceiptResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"O\n" +
	"\x17SendTypingStatusRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1b\n" +
	"\tis_typing\x18\x02 \x01(\bR\bisTyping\"2\n" +
	"\x18SendTypingStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"T\n" +
	" AddParticipantToGroupChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\";\n" +
	"!AddParticipantToGroupChatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"Y\n" +
	"%RemoveParticipantFromGroupChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"@\n" +
	"&RemoveParticipantFromGroupChatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"C\n" +
	"\x14EditGroupChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"/\n" +
	"\x15EditGroupChatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"1\n" +
	"\x16DeleteGroupChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"1\n" +
	"\x17DeleteGroupChatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"0\n" +
	"\x15LeaveGroupChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"0\n" +
	"\x16LeaveGroupChatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"I\n" +
	"\x15StreamMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"G\n" +
	"\x16StreamMessagesResponse\x12-\n" +
	"\amessage\x18\x01 \x01(\v2\x13.chatpb.ChatMessageR\amessage2\x81\n" +
	"\n" +
	"\vChatService\x12=\n" +
	"\bGetChats\x12\x17.chatpb.GetChatsRequest\x1a\x18.chatpb.GetChatsResponse\x12U\n" +
	"\x10CreateDirectChat\x12\x1f.chatpb.CreateDirectChatRequest\x1a .chatpb.CreateDirectChatResponse\x12R\n" +
	"\x0fCreateGroupChat\x12\x1e.chatpb.CreateGroupChatRequest\x1a\x1f.chatpb.CreateGroupChatResponse\x12F\n" +
	"\vSendMessage\x12\x1a.chatpb.SendMessageRequest\x1a\x1b.chatpb.SendMessageResponse\x12F\n" +
	"\vGetMessages\x12\x1a.chatpb.GetMessagesRequest\x1a\x1b.chatpb.GetMessagesResponse\x12F\n" +
	"\vEditMessage\x12\x1a.chatpb.EditMessageRequest\x1a\x1b.chatpb.EditMessageResponse\x12L\n" +
	"\rDeleteMessage\x12\x1c.chatpb.DeleteMessageRequest\x1a\x1d.chatpb.DeleteMessageResponse\x12R\n" +
	"\x0fSendReadReceipt\x12\x1e.chatpb.SendReadReceiptRequest\x1a\x1f.chatpb.SendReadReceiptResponse\x12U\n" +
	"\x10SendTypingStatus\x12\x1f.chatpb.SendTypingStatusRequest\x1a .chatpb.SendTypingStatusResponse\x12p\n" +
	"\x19AddParticipantToGroupChat\x12(.chatpb.AddParticipantToGroupChatRequest\x1a).chatpb.AddParticipantToGroupChatResponse\x12\x7f\n" +
	"\x1eRemoveParticipantFromGroupChat\x12-.chatpb.RemoveParticipantFromGroupChatRequest\x1a..chatpb.RemoveParticipantFromGroupChatResponse\x12L\n" +
	"\rEditGroupChat\x12\x1c.chatpb.EditGroupChatRequest\x1a\x1d.chatpb.EditGroupChatResponse\x12R\n" +
	"\x0fDeleteGroupChat\x12\x1e.chatpb.DeleteGroupChatRequest\x1a\x1f.chatpb.DeleteGroupChatResponse\x12O\n" +
	"\x0eLeaveGroupChat\x12\x1d.chatpb.LeaveGroupChatRequest\x1a\x1e.chatpb.LeaveGroupChatResponse\x12Q\n" +
	"\x0eStreamMessages\x12\x1d.chatpb.StreamMessagesRequest\x1a\x1e.chatpb.StreamMessagesResponse0\x01B;Z9github.com/IsFariza/maxat-protobuf/chat-service-pb;chatpbb\x06proto3"

var (
	file_chat_service_pb_chat_proto_rawDescOnce sync.Once
	file_chat_service_pb_chat_proto_rawDescData []byte
)

func file_chat_service_pb_chat_proto_rawDescGZIP() []byte {
	file_chat_service_pb_chat_proto_rawDescOnce.Do(func() {
		file_chat_service_pb_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_service_pb_chat_proto_rawDesc), len(file_chat_service_pb_chat_proto_rawDesc)))
	})
	return file_chat_service_pb_chat_proto_rawDescData
}

var file_chat_service_pb_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_chat_service_pb_chat_proto_goTypes = []any{
	(*Chat)(nil),                                   // 0: chatpb.Chat
	(*ChatMessage)(nil),                            // 1: chatpb.ChatMessage
	(*GetChatsRequest)(nil),                        // 2: chatpb.GetChatsRequest
	(*GetChatsResponse)(nil),                       // 3: chatpb.GetChatsResponse
	(*CreateDirectChatRequest)(nil),                // 4: chatpb.CreateDirectChatRequest
	(*CreateDirectChatResponse)(nil),               // 5: chatpb.CreateDirectChatResponse
	(*CreateGroupChatRequest)(nil),                 // 6: chatpb.CreateGroupChatRequest
	(*CreateGroupChatResponse)(nil),                // 7: chatpb.CreateGroupChatResponse
	(*SendMessageRequest)(nil),                     // 8: chatpb.SendMessageRequest
	(*SendMessageResponse)(nil),                    // 9: chatpb.SendMessageResponse
	(*GetMessagesRequest)(nil),                     // 10: chatpb.GetMessagesRequest
	(*GetMessagesResponse)(nil),                    // 11: chatpb.GetMessagesResponse
	(*EditMessageRequest)(nil),                     // 12: chatpb.EditMessageRequest
	(*EditMessageResponse)(nil),                    // 13: chatpb.EditMessageResponse
	(*DeleteMessageRequest)(nil),                   // 14: chatpb.DeleteMessageRequest
	(*DeleteMessageResponse)(nil),                  // 15: chatpb.DeleteMessageResponse
	(*SendReadReceiptRequest)(nil),                 // 16: chatpb.SendReadReceiptRequest
	(*SendReadReceiptResponse)(nil),                // 17: chatpb.SendReadReceiptResponse
	(*SendTypingStatusRequest)(nil),                // 18: chatpb.SendTypingStatusRequest
	(*SendTypingStatusResponse)(nil),               // 19: chatpb.SendTypingStatusResponse
	(*AddParticipantToGroupChatRequest)(nil),       // 20: chatpb.AddParticipantToGroupChatRequest
	(*AddParticipantToGroupChatResponse)(nil),      // 21: chatpb.AddParticipantToGroupChatResponse
	(*RemoveParticipantFromGroupChatRequest)(nil),  // 22: chatpb.RemoveParticipantFromGroupChatRequest
	(*RemoveParticipantFromGroupChatResponse)(nil), // 23: chatpb.RemoveParticipantFromGroupChatResponse
	(*EditGroupChatRequest)(nil),                   // 24: chatpb.EditGroupChatRequest
	(*EditGroupChatResponse)(nil),                  // 25: chatpb.EditGroupChatResponse
	(*DeleteGroupChatRequest)(nil),                 // 26: chatpb.DeleteGroupChatRequest
	(*DeleteGroupChatResponse)(nil),                // 27: chatpb.DeleteGroupChatResponse
	(*LeaveGroupChatRequest)(nil),                  // 28: chatpb.LeaveGroupChatRequest
	(*LeaveGroupChatResponse)(nil),                 // 29: chatpb.LeaveGroupChatResponse
	(*StreamMessagesRequest)(nil),                  // 30: chatpb.StreamMessagesRequest
	(*StreamMessagesResponse)(nil),                 // 31: chatpb.StreamMessagesResponse
	(*timestamppb.Timestamp)(nil),                  // 32: google.protobuf.Timestamp
}
var file_chat_service_pb_chat_proto_depIdxs = []int32{
	32, // 0: chatpb.Chat.created_at:type_name -> google.protobuf.Timestamp
	1,  // 1: chatpb.Chat.last_message:type_name -> chatpb.ChatMessage
	32, // 2: chatpb.ChatMessage.created_at:type_name -> google.protobuf.Timestamp
	32, // 3: chatpb.ChatMessage.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: chatpb.GetChatsResponse.chats:type_name -> chatpb.Chat
	0,  // 5: chatpb.CreateDirectChatResponse.chat:type_name -> chatpb.Chat
	0,  // 6: chatpb.CreateGroupChatResponse.chat:type_name -> chatpb.Chat
	1,  // 7: chatpb.SendMessageResponse.message:type_name -> chatpb.ChatMessage
	1,  // 8: chatpb.GetMessagesResponse.messages:type_name -> chatpb.ChatMessage
	1,  // 9: chatpb.EditMessageResponse.message:type_name -> chatpb.ChatMessage
	1,  // 10: chatpb.StreamMessagesResponse.message:type_name -> chatpb.ChatMessage
	2,  // 11: chatpb.ChatService.GetChats:input_type -> chatpb.GetChatsRequest
	4,  // 12: chatpb.ChatService.CreateDirectChat:input_type -> chatpb.CreateDirectChatRequest
	6,  // 13: chatpb.ChatService.CreateGroupChat:input_type -> chatpb.CreateGroupChatRequest
	8,  // 14: chatpb.ChatService.SendMessage:input_type -> chatpb.SendMessageRequest
	10, // 15: chatpb.ChatService.GetMessages:input_type -> chatpb.GetMessagesRequest
	12, // 16: chatpb.ChatService.EditMessage:input_type -> chatpb.EditMessageRequest
	14, // 17: chatpb.ChatService.DeleteMessage:input_type -> chatpb.DeleteMessageRequest
	16, // 18: chatpb.ChatService.SendReadReceipt:input_type -> chatpb.SendReadReceiptRequest
	18, // 19: chatpb.ChatService.SendTypingStatus:input_type -> chatpb.SendTypingStatusRequest
	20, // 20: chatpb.ChatService.AddParticipantToGroupChat:input_type -> chatpb.AddParticipantToGroupChatRequest
	22, // 21: chatpb.ChatService.RemoveParticipantFromGroupChat:input_type -> chatpb.RemoveParticipantFromGroupChatRequest
	24, // 22: chatpb.ChatService.EditGroupChat:input_type -> chatpb.EditGroupChatRequest
	26, // 23: chatpb.ChatService.DeleteGroupChat:input_type -> chatpb.DeleteGroupChatRequest
	28, // 24: chatpb.ChatService.LeaveGroupChat:input_type -> chatpb.LeaveGroupChatRequest
	30, // 25: chatpb.ChatService.StreamMessages:input_type -> chatpb.StreamMessagesRequest
	3,  // 26: chatpb.ChatService.GetChats:output_type -> chatpb.GetChatsResponse
	5,  // 27: chatpb.ChatService.CreateDirectChat:output_type -> chatpb.CreateDirectChatResponse
	7,  // 28: chatpb.ChatService.CreateGroupChat:output_type -> chatpb.CreateGroupChatResponse
	9,  // 29: chatpb.ChatService.SendMessage:output_type -> chatpb.SendMessageResponse
	11, // 30: chatpb.ChatService.GetMessages:output_type -> chatpb.GetMessagesResponse
	13, // 31: chatpb.ChatService.EditMessage:output_type -> chatpb.EditMessageResponse
	15, // 32: chatpb.ChatService.DeleteMessage:output_type -> chatpb.DeleteMessageResponse
	17, // 33: chatpb.ChatService.SendReadReceipt:output_type -> chatpb.SendReadReceiptResponse
	19, // 34: chatpb.ChatService.SendTypingStatus:output_type -> chatpb.SendTypingStatusResponse
	21, // 35: chatpb.ChatService.AddParticipantToGroupChat:output_type -> chatpb.AddParticipantToGroupChatResponse
	23, // 36: chatpb.ChatService.RemoveParticipantFromGroupChat:output_type -> chatpb.RemoveParticipantFromGroupChatResponse
	25, // 37: chatpb.ChatService.EditGroupChat:output_type -> chatpb.EditGroupChatResponse
	27, // 38: chatpb.ChatService.DeleteGroupChat:output_type -> chatpb.DeleteGroupChatResponse
	29, // 39: chatpb.ChatService.LeaveGroupChat:output_type -> chatpb.LeaveGroupChatResponse
	31, // 40: chatpb.ChatService.StreamMessages:output_type -> chatpb.StreamMessagesResponse
	26, // [26:41] is the sub-list for method output_type
	11, // [11:26] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_chat_service_pb_chat_proto_init() }
func file_chat_service_pb_chat_proto_init() {
	if File_chat_service_pb_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_service_pb_chat_proto_rawDesc), len(file_chat_service_pb_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_service_pb_chat_proto_goTypes,
		DependencyIndexes: file_chat_service_pb_chat_proto_depIdxs,
		MessageInfos:      file_chat_service_pb_chat_proto_msgTypes,
	}.Build()
	File_chat_service_pb_chat_proto = out.File
	file_chat_service_pb_chat_proto_goTypes = nil
	file_chat_service_pb_chat_proto_depIdxs = nil
}
